// Bahasa Indonesia for the built-in auto-commentary lines — natural, hype,
// Gen-Z esports-caster slang (bukan terjemahan kaku). Think MLBB/streamer
// energy: "war", "cuan", "gacor", "embat", "keancem", "auto", "sadis", "OP".
// Keyed by the exact English template so {placeholders} carry over. In-game
// terms stay English on purpose (Lord, Turtle, Tower, gold, net worth, K/D/A,
// MVP); team/player/hero names come from {placeholders} so they stay original.

export const ID_TEMPLATES: Record<string, string> = {
  // ── net worth ──────────────────────────────────────────────────────
  "{lead} are running away with this — a {diff} gold lead.": "{lead} auto kabur nih, gap gold-nya udah {diff}!",
  "It's turning into a stranglehold; {lead} up {diff} in net worth.": "Mulai dicekik nih, {lead} unggul {diff} di net worth.",
  "{lead} in complete control of the gold, ahead by {diff}.": "{lead} pegang penuh gold, kepisah {diff}.",
  "This is a landslide on the economy — {lead} plus {diff}.": "Ekonominya jomplang parah — {lead} plus {diff}.",
  "{lead} have broken the game open, {diff} clear on gold.": "{lead} udah buka jarak, gold kepisah {diff}.",
  "The net worth gap is brutal now: {lead} up {diff}.": "Gap net worth-nya sadis sekarang: {lead} unggul {diff}.",
  "{lead} snowballing hard, a {diff} advantage and climbing.": "{lead} nge-snowball parah, unggul {diff} dan makin gacor.",
  "Dead even on gold — less than {diff} between them.": "Gold-nya nempel banget — kepisah nggak nyampe {diff}.",
  "Anyone's game here, the net worth is razor thin.": "Bisa siapa aja nih, net worth-nya tipis-tipis.",
  "Neck and neck; neither side can find a gold cushion.": "Salip-salipan; nggak ada yang bisa dapet jarak aman gold.",
  "You couldn't slide a coin between these two on gold.": "Soal gold, dua tim ini mepet banget nggak ada celah.",
  "The economy is a stalemate — under {diff} separating them.": "Ekonominya buntu — kepisah nggak sampe {diff}.",
  "Nothing to choose on net worth, it's a genuine coin flip.": "Net worth-nya seri, ini mah lempar koin.",
  "Both sides matching each other gold for gold.": "Dua tim saling nyamain gold, imbang terus.",
  "{lead} nose in front by {diff} in gold.": "{lead} unggul tipis {diff} di gold.",
  "A working advantage for {lead}, {diff} up on net worth.": "Keunggulan yang kepake buat {lead}, plus {diff} di net worth.",
  "{lead} edging the economy, {diff} to the good.": "{lead} sedikit ngungguli ekonomi, plus {diff}.",
  "It's {lead} with the gold cushion now — {diff} clear.": "Sekarang {lead} yang punya jarak aman gold — kepisah {diff}.",
  "{lead} building something here, {diff} up on net worth.": "{lead} lagi nyusun nih, unggul {diff} di net worth.",
  "The economy tilts {lead}'s way, a {diff} lead.": "Ekonominya miring ke {lead}, unggul {diff}.",
  "{trail} clawing back — they've shaved {closed} off the deficit.": "{trail} mulai ngejar — udah motong {closed} dari ketinggalan!",
  "The gap is closing; {trail} back within {diff}.": "Gap-nya nutup nih; {trail} balik ke {diff} doang.",
  "{trail} chipping into the lead, {closed} of it gone already.": "{trail} mulai gerogotin, {closed} udah kepotong.",
  "Momentum with {trail} — the deficit's down to {diff}.": "Momentum di {trail} — ketinggalannya tinggal {diff}.",
  "{trail} refusing to fold, {closed} clawed back off the gold gap.": "{trail} kekeh nggak nyerah, {closed} kekejar dari gap gold.",
  "Lead has flipped — {lead} now ahead on gold.": "Keunggulan kebalik — sekarang {lead} yang mimpin gold!",
  "Momentum swing! {lead} have taken over the net worth lead.": "Momentum balik! {lead} ambil alih pimpinan net worth.",
  "The gold lead changes hands — it's {lead} in front now.": "Pimpinan gold pindah tangan — sekarang giliran {lead}.",
  "{lead} have turned it around and now hold the economy edge.": "{lead} berhasil balikin keadaan, sekarang unggul ekonomi.",
  "Complete reversal on net worth — {lead} on top by {diff}.": "Bener-bener kebalik di net worth — {lead} unggul {diff}.",

  // ── team kills ─────────────────────────────────────────────────────
  "{lead} bullying the scoreboard, {hi}–{lo} on kills.": "{lead} ngebully papan skor, {hi}–{lo} di kills.",
  "{lead} with a commanding {hi}–{lo} kill lead.": "{lead} unggul jauh {hi}–{lo} di kills.",
  "{lead} winning every fight that matters — {hi}–{lo}.": "{lead} menang di tiap war penting — {hi}–{lo}.",
  "It's one-way traffic on the kill feed, {lead} up {hi}–{lo}.": "Kill feed-nya sepihak, {lead} unggul {hi}–{lo}.",
  "{lead} dictating the pace, {hi} kills to {lo}.": "{lead} yang ngatur tempo, {hi} kills lawan {lo}.",
  "The scoreboard says it all: {lead} {hi}, {trail} {lo}.": "Papan skor udah jelasin semua: {lead} {hi}, {trail} {lo}.",
  "Bloodbath and it's even — {hi}–{lo} on the kill count.": "Berdarah-darah tapi imbang — {hi}–{lo} di kill count.",
  "Both teams trading everything, {a}–{b} in kills.": "Dua tim saling tuker, {a}–{b} di kills.",
  "A proper slugfest, blows landing both ways at {a}–{b}.": "Baku hantam beneran, dua-duanya kena di {a}–{b}.",
  "Neither side backing down — {a}–{b} and every fight is a scrap.": "Nggak ada yang mau ngalah — {a}–{b} dan tiap war ribut.",
  "End to end stuff, the kills level at {hi}–{lo}.": "Bolak-balik seru, kills imbang di {hi}–{lo}.",
  "They are trading punches, {a}–{b} and nothing given easy.": "Saling balas, {a}–{b} dan nggak ada yang gratis.",
  "Teamfight just erupted — {count} kills in a blink.": "War baru aja pecah — {count} kills dalam sekejap!",
  "A skirmish breaks out, {count} down in quick succession.": "Ribut kecil pecah, {count} tumbang beruntun.",
  "It's kicked off! {count} taken in the scramble.": "Pecah nih! {count} kena di keributan.",
  "Chaos in the fight — {count} kills traded already.": "Chaos di war — {count} kills udah ketuker.",
  "The dam breaks: {count} go down at once.": "Bendungan jebol: {count} tumbang barengan.",
  "Big fight, big swing — {count} on the feed just like that.": "War gede, swing gede — {count} masuk feed gitu aja.",
  "{scorer} pick up a kill to keep the pressure on.": "{scorer} dapet kill, tekanan tetep jalan.",
  "The next one goes to {scorer}.": "Yang berikutnya punya {scorer}.",
  "{scorer} find a pick and tilt the numbers.": "{scorer} dapet pick, angkanya geser.",
  "First blood of this exchange belongs to {scorer}.": "Darah pertama di bentrokan ini punya {scorer}.",
  "{scorer} catch one out — advantage pressed.": "{scorer} nyomot satu — keunggulan ditekan.",
  "A clean pickoff for {scorer}.": "Pickoff bersih buat {scorer}.",

  // ── tower ──────────────────────────────────────────────────────────
  "{team} crack another tower — up to {count} now.": "{team} jebol Tower lagi — jadi {count} sekarang.",
  "Structure falls; {team} take tower number {count}.": "Bangunan tumbang; {team} ambil Tower ke-{count}.",
  "{team} keep chipping the map, {count} towers down.": "{team} terus gerogotin map, {count} Tower roboh.",
  "Another one gone — {team} now on {count} towers.": "Satu lagi ilang — {team} sekarang {count} Tower.",
  "{team} pry open the map, {count} structures to their name.": "{team} buka map, {count} bangunan atas nama mereka.",
  "Tower down for {team}, that's {count} in the bank.": "Tower roboh buat {team}, jadi {count} nih.",
  "{team} trade the fight for a tower — {count} total.": "{team} tuker war sama Tower — total {count}.",
  "{leader} own the map — {hi} towers to {lo}.": "{leader} nguasain map — {hi} Tower lawan {lo}.",
  "Territory is all {leader}: {hi} towers to {lo}.": "Teritorinya {leader} semua: {hi} Tower lawan {lo}.",
  "{leader} have the map choked, {hi}–{lo} on structures.": "{leader} nyekik map, {hi}–{lo} di bangunan.",
  "Half the map belongs to {leader}, {hi} towers to {lo}.": "Separuh map punya {leader}, {hi} Tower lawan {lo}.",

  // ── turtle ─────────────────────────────────────────────────────────
  "{team} slam the Turtle for the gold and buff.": "{team} embat Turtle, dapet gold sama buff-nya.",
  "Turtle goes to {team} — a tidy pickup.": "Turtle jatuh ke {team} — pickup yang rapi.",
  "{team} secure the Turtle, gold for the whole squad.": "{team} amanin Turtle, gold buat satu tim.",
  "That's the Turtle for {team}, momentum and money.": "Turtle buat {team}, dapet momentum plus cuan.",
  "{team} bank the Turtle without a fuss.": "{team} kantongin Turtle santai aja.",
  "Easy gold for {team} off the back of that Turtle.": "Gold gampang buat {team} dari Turtle itu.",

  // ── lord ───────────────────────────────────────────────────────────
  "{team} secure the LORD — this could be the game-ender.": "{team} amanin LORD — ini bisa jadi penutup game!",
  "Lord is down and it belongs to {team}. Massive.": "Lord tumbang dan jadi punya {team}. Gede banget!",
  "{team} take Lord and now they march.": "{team} ambil Lord, sekarang tinggal maju.",
  "The Lord is {team}'s — the siege is coming.": "Lord punya {team} — siap-siap dikepung.",
  "{team} slay the Lord; this is a match-defining call.": "{team} bunuh Lord; ini call penentu match.",
  "Huge for {team} — Lord in the bag and pushing.": "Gede buat {team} — Lord di kantong, langsung push.",
  "{team} get the Lord and now the base is under threat.": "{team} dapet Lord, sekarang base lawan keancem.",

  // ── player K/D/A ───────────────────────────────────────────────────
  "{player} is unkillable — {k} kills and yet to fall.": "{player} nggak bisa dibunuh — {k} kills dan belum mati!",
  "Nobody can touch {player}: {k}/{d}/{a}.": "Nggak ada yang bisa nyentuh {player}: {k}/{d}/{a}.",
  "{player} is on a different level, {k} kills without a death.": "{player} beda level, {k} kills tanpa mati.",
  "A flawless game so far from {player} — {k}/{d}/{a}.": "Game bersih banget dari {player} — {k}/{d}/{a}.",
  "{player} untouchable, {k} to their name and still standing.": "{player} nggak tersentuh, {k} kills dan masih berdiri.",
  "{player} is taking over — {k}/{d}/{a} on the board.": "{player} mulai ngambil alih — {k}/{d}/{a} di papan.",
  "{player} everywhere on the map, already {ka} takedowns involved.": "{player} ada di mana-mana, udah {ka} takedown kelibat.",
  "{player} carrying the load, {ka} kills and assists so far.": "{player} yang carry, {ka} kills sama assist sejauh ini.",
  "This is the {player} show — {k}/{d}/{a}.": "Ini panggungnya {player} — {k}/{d}/{a}.",
  "{player} stamping their name on this game, {ka} involvements.": "{player} nulis nama di game ini, {ka} keterlibatan.",
  "{player} having a real say in this one — {k}/{d}/{a}.": "{player} punya andil gede — {k}/{d}/{a}.",
  "{player} racking up the involvement, {ka} kills and assists.": "{player} numpuk kontribusi, {ka} kills sama assist.",
  "{player} showing up in the fights, {k}/{d}/{a}.": "{player} nongol di tiap war, {k}/{d}/{a}.",
  "Good game building for {player}: {ka} takedowns involved.": "Game bagus lagi kebangun buat {player}: {ka} takedown kelibat.",
  "{player} making their presence felt, {k}/{d}/{a}.": "{player} bikin kehadirannya kerasa, {k}/{d}/{a}.",
  "Rough one for {player}, caught out {d} times now.": "Apes buat {player}, udah ketangkep {d} kali.",
  "{player} can't buy a break — down {d} deaths.": "{player} lagi sial banget — udah {d} kali mati.",
  "The opposition are hunting {player}, {d} times already.": "Lawan lagi ngeburu {player}, udah {d} kali.",
  "{player} having a nightmare, {k}/{d}/{a} on the game.": "{player} lagi mimpi buruk, {k}/{d}/{a} di game ini.",
  "It's not falling for {player} — {d} deaths and counting.": "Lagi nggak jalan buat {player} — {d} deaths dan nambah.",

  // ── win probability ────────────────────────────────────────────────
  "The model has {favored} firmly in front — {pct}% to close it out.": "Model naruh {favored} jelas di depan — {pct}% buat nutup.",
  "{favored} in the driver's seat at {pct}% win chance.": "{favored} pegang kendali di {pct}% peluang menang.",
  "The numbers love {favored} here, {pct}% to win it.": "Angkanya sayang sama {favored}, {pct}% buat menang.",
  "{favored} heavy favourites now — {pct}% on the model.": "{favored} favorit berat sekarang — {pct}% di model.",
  "It's {favored}'s to lose, the read sits at {pct}%.": "Tinggal {favored} yang jaga, bacaannya {pct}%.",
  "Momentum swinging toward {to} on the win-probability read.": "Momentum geser ke {to} di bacaan win-probability.",
  "The needle moves for {to} — this is where games turn.": "Jarumnya gerak ke {to} — di sini game biasanya balik.",
  "{to} tilting the odds their way now.": "{to} mulai miringin peluang ke mereka.",
  "Big shift on the model, and it's {to} climbing.": "Pergeseran gede di model, {to} yang naik.",
  "The win probability lurches toward {to}.": "Win probability-nya loncat ke {to}.",

  // ── hero flavor ────────────────────────────────────────────────────
  "{hero} in the hands of {player} is a real problem right now.": "{hero} di tangan {player} beneran ngeri sekarang.",
  "Watch the {hero} — {player} is finding all the angles.": "Awas {hero}-nya — {player} nemu semua celah.",
  "{player}'s {hero} looking like the pick of the draft.": "{hero}-nya {player} kayak pick terbaik di draft.",
  "{player} has the {hero} humming — a menace in every fight.": "{player} bikin {hero} jalan mulus — ngeri di tiap war.",
  "That {hero} pick is paying off for {player}.": "Pick {hero} itu kebayar buat {player}.",
  "{player} making the {hero} look broken right now.": "{player} bikin {hero} keliatan OP banget sekarang.",

  // ── general pacing ─────────────────────────────────────────────────
  "Still early doors — both sides settling into the farm.": "Masih early game — dua tim anteng farming dulu.",
  "Opening exchanges, feeling each other out.": "Baru pembukaan, masih saling raba.",
  "Laning phase in full swing, last hits and level leads for now.": "Fase laning lagi rame, rebutan last hit sama unggul level.",
  "Quiet start — everyone's heads down farming.": "Awalan adem — semua fokus farming.",
  "Early game jostling for the jungle and lane priority.": "Early game rebutan jungle sama prioritas lane.",
  "Mid game and the map is opening up — objectives on the horizon.": "Mid game, map mulai kebuka — objektif udah keliatan.",
  "Rotations getting sharper as we hit the mid game.": "Rotasi makin tajem pas masuk mid game.",
  "The game's stretching its legs now — expect the fights to start.": "Game-nya mulai panas — siap-siap war pecah.",
  "Cores coming online, and the tempo is picking up.": "Core mulai jadi, tempo-nya naik.",
  "Mid game chess — positioning and vision for the next objective.": "Catur mid game — soal posisi sama vision buat objektif berikutnya.",
  "Deep into the late game — one fight decides it from here.": "Udah dalem ke late game — satu war nentuin dari sini.",
  "Every pick matters now; there's no respawning your way out of a bad one.": "Tiap pick penting sekarang; salah dikit nggak ketolong respawn.",
  "The stakes are climbing — full builds and long respawns.": "Taruhannya makin tinggi — build full, respawn lama.",
  "This is the business end; a single mistake could be terminal.": "Ini bagian seriusnya; satu kesalahan bisa fatal.",
  "Late game tension — both sides walking on eggshells around the map.": "Tegang late game — dua tim jalan hati-hati di map.",
  "We are into the danger zone past 18 minutes — respawns are long and one clean pick ends it.": "Udah masuk zona bahaya lewat menit 18 — respawn lama, satu pick bersih bisa nutup game.",
  "Every base race and Lord call is match point now — nerves of steel required.": "Tiap base race sama call Lord udah match point — butuh mental baja.",
  "This is where legends are made — a single teamfight from here writes the result.": "Di sinilah legenda lahir — satu war dari sini nentuin hasil.",
  "Deep, deep late game — buybacks of momentum only; there's no farming your way back now.": "Late game dalem banget — cuma momentum yang ngomong; nggak bisa farming buat balik.",
  "Sudden-death territory now — one thrown fight and it's over.": "Zona sudden-death sekarang — sekali war kebuang, tamat.",
  "Everything on a knife's edge past 18 — the next objective could end it.": "Semua di ujung tanduk lewat menit 18 — objektif berikutnya bisa nutup.",
};

// Win-probability interjection phrasings in Bahasa Indonesia (casual caster).
export const ID_WINPROB = {
  even: [
    "Win probability imbang banget — {teamA} {aPct}%, {teamB} {bPct}%.",
    "Model-nya bingung misahin: {aPct}% / {bPct}%.",
    "Seri di bacaan win-probability, {teamA} {aPct}% lawan {teamB} {bPct}%.",
    "Terlalu tipis buat ditebak — {aPct}% lawan {bPct}% di model.",
    "Nggak ada bedanya: {teamA} {aPct}%, {teamB} {bPct}%.",
  ],
  heavy: [
    "{favored} favorit berat sekarang — {favPct}% buat menang.",
    "Jarumnya nempel ke {favored} di {favPct}%.",
    "{favored} lagi di atas angin, {favPct}% di model.",
    "Tinggal {favored} yang jaga — {favPct}% di bacaan win-probability.",
    "Model-nya hampir manggil: {favored} {favPct}%.",
  ],
  lean: [
    "Win probability condong ke {favored} di {favPct}%.",
    "{favored} favorit buat sekarang, {favPct}% buat nutup.",
    "Sedikit unggul buat {favored} — {favPct}% di bacaan.",
    "{favored} maju tipis di model, {favPct}%.",
    "Peluangnya miring ke {favored}, {favPct}% lawan {rest}%.",
  ],
};
