// Bahasa Indonesia for the built-in auto-commentary — written like a real
// Indonesian MLBB caster talks, not a word-for-word translation. Natural,
// human, idiomatic: same meaning/context, freely reworded. No gambling-adjacent
// slang ("cuan"/"gacor" are intentionally avoided). Keyed by the exact English
// template so {placeholders} carry over. In-game terms stay English (Lord,
// Turtle, Tower, gold, net worth, K/D/A, MVP); names come from {placeholders}.

export const ID_TEMPLATES: Record<string, string> = {
  // ── opening read (first ~90s) ───────────────────────────────────────
  "And we're underway — {teamA} against {teamB}, draft locked and lanes assigned.": "Pertandingan dimulai — {teamA} lawan {teamB}, draft udah fix, lane udah kebagi.",
  "Here we go: {teamA} versus {teamB}. The draft's done the talking, now the map decides.": "Kita mulai: {teamA} vs {teamB}. Draft udah ngomong, sekarang giliran map yang nentuin.",
  "Fresh game, fresh draft — {teamA} and {teamB} settling into their lanes.": "Game baru, draft baru — {teamA} sama {teamB} mulai nyaman di lane masing-masing.",
  "Game on between {teamA} and {teamB}; let's see whose composition comes online first.": "Game jalan antara {teamA} sama {teamB}; kita liat komposisi siapa yang nyala duluan.",
  "Picks are in — {teamA} and {teamB} feeling out the early map before the fights start.": "Pick udah kelar — {teamA} sama {teamB} baca-baca map dulu sebelum rame.",
  "Early read on the draft — {heroA} and {heroB} look like the pieces this game bends around.": "Baca awal draft — {heroA} sama {heroB} kayaknya jadi kunci jalannya game ini.",
  "Composition-wise, keep an eye on {heroA} and {heroB} as the win conditions here.": "Dari komposisi, pantengin {heroA} sama {heroB} sebagai win condition di sini.",
  "The draft points to {heroA} and {heroB} setting the tempo for their sides.": "Draft-nya ngarah ke {heroA} sama {heroB} yang bakal ngatur tempo timnya.",
  "Plenty to like in this draft — {heroA} and {heroB} the ones to watch early.": "Draft-nya menarik — {heroA} sama {heroB} yang patut diliat di awal.",
  // ── net worth ──────────────────────────────────────────────────────
  "{lead} are running away with this — a {diff} gold lead.": "{lead} makin ngacir nih, unggul {diff} gold!",
  "It's turning into a stranglehold; {lead} up {diff} in net worth.": "Mulai dicekik, {lead} unggul {diff} net worth.",
  "{lead} in complete control of the gold, ahead by {diff}.": "{lead} pegang kendali penuh, unggul {diff} gold.",
  "This is a landslide on the economy — {lead} plus {diff}.": "Ekonominya timpang jauh — {lead} plus {diff}.",
  "{lead} have broken the game open, {diff} clear on gold.": "{lead} udah bikin jarak, unggul {diff} gold.",
  "The net worth gap is brutal now: {lead} up {diff}.": "Selisih net worth-nya udah kejam: {lead} unggul {diff}.",
  "{lead} snowballing hard, a {diff} advantage and climbing.": "{lead} makin ngegas, unggul {diff} dan terus nambah.",
  "Dead even on gold — less than {diff} between them.": "Gold-nya nempel — selisih nggak sampe {diff}.",
  "Anyone's game here, the net worth is razor thin.": "Masih bisa dibalik nih, net worth-nya tipis.",
  "Neck and neck; neither side can find a gold cushion.": "Kejar-kejaran; nggak ada yang bisa lepas jarak gold.",
  "You couldn't slide a coin between these two on gold.": "Gold dua tim ini nempel banget, susah dibedain.",
  "The economy is a stalemate — under {diff} separating them.": "Ekonominya mentok imbang — selisih di bawah {diff}.",
  "Nothing to choose on net worth, it's a genuine coin flip.": "Net worth-nya bener-bener seri, fifty-fifty.",
  "Both sides matching each other gold for gold.": "Dua tim saling ngimbangin gold.",
  "{lead} nose in front by {diff} in gold.": "{lead} unggul tipis {diff} gold.",
  "A working advantage for {lead}, {diff} up on net worth.": "Keunggulan yang berarti buat {lead}, plus {diff} net worth.",
  "{lead} edging the economy, {diff} to the good.": "{lead} sedikit ngungguli ekonomi, plus {diff}.",
  "It's {lead} with the gold cushion now — {diff} clear.": "Sekarang {lead} yang punya jarak gold — unggul {diff}.",
  "{lead} building something here, {diff} up on net worth.": "{lead} lagi nyusun kekuatan, unggul {diff} net worth.",
  "The economy tilts {lead}'s way, a {diff} lead.": "Ekonominya condong ke {lead}, unggul {diff}.",
  "{trail} clawing back — they've shaved {closed} off the deficit.": "{trail} mulai ngejar — udah motong {closed} dari ketinggalan!",
  "The gap is closing; {trail} back within {diff}.": "Jaraknya nutup; {trail} balik ke selisih {diff}.",
  "{trail} chipping into the lead, {closed} of it gone already.": "{trail} mulai ngikis keunggulan, {closed} udah kepangkas.",
  "Momentum with {trail} — the deficit's down to {diff}.": "Momentum ada di {trail} — ketinggalan tinggal {diff}.",
  "{trail} refusing to fold, {closed} clawed back off the gold gap.": "{trail} nggak mau nyerah, {closed} kekejar dari selisih gold.",
  "Lead has flipped — {lead} now ahead on gold.": "Keunggulan berbalik — sekarang {lead} yang mimpin gold!",
  "Momentum swing! {lead} have taken over the net worth lead.": "Momentum berbalik! {lead} ngambil alih pimpinan net worth.",
  "The gold lead changes hands — it's {lead} in front now.": "Pimpinan gold pindah tangan — giliran {lead} sekarang.",
  "{lead} have turned it around and now hold the economy edge.": "{lead} berhasil balikin keadaan, unggul ekonomi sekarang.",
  "Complete reversal on net worth — {lead} on top by {diff}.": "Bener-bener berbalik di net worth — {lead} unggul {diff}.",

  // ── team kills ─────────────────────────────────────────────────────
  "{lead} bullying the scoreboard, {hi}–{lo} on kills.": "{lead} ngebully papan skor, {hi}–{lo}.",
  "{lead} with a commanding {hi}–{lo} kill lead.": "{lead} unggul telak {hi}–{lo} di kill.",
  "{lead} winning every fight that matters — {hi}–{lo}.": "{lead} menang di tiap war penting — {hi}–{lo}.",
  "It's one-way traffic on the kill feed, {lead} up {hi}–{lo}.": "Kill feed-nya sepihak, {lead} unggul {hi}–{lo}.",
  "{lead} dictating the pace, {hi} kills to {lo}.": "{lead} yang ngatur tempo, {hi} kill lawan {lo}.",
  "The scoreboard says it all: {lead} {hi}, {trail} {lo}.": "Papan skor udah ngomong: {lead} {hi}, {trail} {lo}.",
  "Bloodbath and it's even — {hi}–{lo} on the kill count.": "Saling bantai tapi imbang — {hi}–{lo} di kill.",
  "Both teams trading everything, {a}–{b} in kills.": "Dua tim saling balas, {a}–{b} di kill.",
  "A proper slugfest, blows landing both ways at {a}–{b}.": "Baku hantam sengit, dua-duanya kena {a}–{b}.",
  "Neither side backing down — {a}–{b} and every fight is a scrap.": "Nggak ada yang mundur — {a}–{b} dan tiap war rusuh.",
  "End to end stuff, the kills level at {hi}–{lo}.": "Seru bolak-balik, kill imbang {hi}–{lo}.",
  "They are trading punches, {a}–{b} and nothing given easy.": "Saling pukul, {a}–{b} nggak ada yang ngasih gratis.",
  "Teamfight just erupted — {count} kills in a blink.": "War baru aja pecah — {count} kill sekejap!",
  "A skirmish breaks out, {count} down in quick succession.": "Bentrok pecah, {count} tumbang beruntun.",
  "It's kicked off! {count} taken in the scramble.": "Pecah! {count} tumbang di keributan.",
  "Chaos in the fight — {count} kills traded already.": "Ricuh di war — {count} kill udah ketuker.",
  "The dam breaks: {count} go down at once.": "Jebol! {count} tumbang sekaligus.",
  "Big fight, big swing — {count} on the feed just like that.": "War gede, swing gede — {count} masuk feed.",
  "{scorer} pick up a kill to keep the pressure on.": "{scorer} dapet kill, tekanan jalan terus.",
  "The next one goes to {scorer}.": "Yang berikutnya buat {scorer}.",
  "{scorer} find a pick and tilt the numbers.": "{scorer} dapet pick, angkanya geser.",
  "First blood of this exchange belongs to {scorer}.": "Darah pertama di bentrok ini punya {scorer}.",
  "{scorer} catch one out — advantage pressed.": "{scorer} nangkep satu — keunggulan ditekan.",
  "A clean pickoff for {scorer}.": "Pick bersih buat {scorer}.",

  // ── tower ──────────────────────────────────────────────────────────
  "{team} crack another tower — up to {count} now.": "{team} jebol Tower lagi — jadi {count}.",
  "Structure falls; {team} take tower number {count}.": "Bangunan tumbang; {team} ambil Tower ke-{count}.",
  "{team} keep chipping the map, {count} towers down.": "{team} terus ngikis map, {count} Tower roboh.",
  "Another one gone — {team} now on {count} towers.": "Satu lagi roboh — {team} sekarang {count} Tower.",
  "{team} pry open the map, {count} structures to their name.": "{team} bongkar map, {count} bangunan atas nama mereka.",
  "Tower down for {team}, that's {count} in the bank.": "Tower roboh buat {team}, total {count}.",
  "{team} trade the fight for a tower — {count} total.": "{team} tuker war sama Tower — total {count}.",
  "{leader} own the map — {hi} towers to {lo}.": "{leader} nguasain map — {hi} Tower lawan {lo}.",
  "Territory is all {leader}: {hi} towers to {lo}.": "Wilayah dikuasai {leader}: {hi} Tower lawan {lo}.",
  "{leader} have the map choked, {hi}–{lo} on structures.": "{leader} nyekik map, {hi}–{lo} di bangunan.",
  "Half the map belongs to {leader}, {hi} towers to {lo}.": "Separuh map punya {leader}, {hi} Tower lawan {lo}.",

  // ── turtle ─────────────────────────────────────────────────────────
  "{team} slam the Turtle for the gold and buff.": "{team} embat Turtle, dapet gold sama buff.",
  "Turtle goes to {team} — a tidy pickup.": "Turtle buat {team} — ambil yang bersih.",
  "{team} secure the Turtle, gold for the whole squad.": "{team} amanin Turtle, gold buat satu tim.",
  "That's the Turtle for {team}, momentum and money.": "Turtle buat {team}, dapet momentum sama gold.",
  "{team} bank the Turtle without a fuss.": "{team} amanin Turtle tanpa ribet.",
  "Easy gold for {team} off the back of that Turtle.": "Gold gampang buat {team} dari Turtle itu.",

  // ── lord ───────────────────────────────────────────────────────────
  "{team} secure the LORD — this could be the game-ender.": "{team} amanin LORD — bisa jadi penutup game!",
  "Lord is down and it belongs to {team}. Massive.": "Lord tumbang, punya {team}. Gede banget!",
  "{team} take Lord and now they march.": "{team} ambil Lord, tinggal maju.",
  "The Lord is {team}'s — the siege is coming.": "Lord punya {team} — siap-siap serbuan.",
  "{team} slay the Lord; this is a match-defining call.": "{team} bunuh Lord; ini keputusan penentu match.",
  "Huge for {team} — Lord in the bag and pushing.": "Gede buat {team} — Lord aman, langsung push.",
  "{team} get the Lord and now the base is under threat.": "{team} dapet Lord, base lawan keancem.",

  // ── player K/D/A ───────────────────────────────────────────────────
  "{player} is unkillable — {k} kills and yet to fall.": "{player} susah dibunuh — {k} kill dan belum mati!",
  "Nobody can touch {player}: {k}/{d}/{a}.": "Nggak ada yang bisa nyentuh {player}: {k}/{d}/{a}.",
  "{player} is on a different level, {k} kills without a death.": "{player} beda kelas, {k} kill tanpa mati.",
  "A flawless game so far from {player} — {k}/{d}/{a}.": "Game bersih dari {player} — {k}/{d}/{a}.",
  "{player} untouchable, {k} to their name and still standing.": "{player} nggak tersentuh, {k} kill dan masih berdiri.",
  "{player} is taking over — {k}/{d}/{a} on the board.": "{player} mulai ngambil alih — {k}/{d}/{a}.",
  "{player} everywhere on the map, already {ka} takedowns involved.": "{player} ada di mana-mana, udah {ka} takedown.",
  "{player} carrying the load, {ka} kills and assists so far.": "{player} yang nge-carry, {ka} kill dan assist.",
  "This is the {player} show — {k}/{d}/{a}.": "Ini panggungnya {player} — {k}/{d}/{a}.",
  "{player} stamping their name on this game, {ka} involvements.": "{player} ninggalin nama di game ini, {ka} kontribusi.",
  "{player} having a real say in this one — {k}/{d}/{a}.": "{player} punya peran gede — {k}/{d}/{a}.",
  "{player} racking up the involvement, {ka} kills and assists.": "{player} numpuk kontribusi, {ka} kill dan assist.",
  "{player} showing up in the fights, {k}/{d}/{a}.": "{player} nongol di tiap war, {k}/{d}/{a}.",
  "Good game building for {player}: {ka} takedowns involved.": "Game bagus lagi kebangun buat {player}: {ka} takedown.",
  "{player} making their presence felt, {k}/{d}/{a}.": "{player} bikin kehadirannya kerasa, {k}/{d}/{a}.",
  "Rough one for {player}, caught out {d} times now.": "Berat buat {player}, udah ketangkep {d} kali.",
  "{player} can't buy a break — down {d} deaths.": "{player} lagi sial — udah {d} kali mati.",
  "The opposition are hunting {player}, {d} times already.": "Lawan lagi ngeburu {player}, udah {d} kali.",
  "{player} having a nightmare, {k}/{d}/{a} on the game.": "{player} lagi mimpi buruk, {k}/{d}/{a}.",
  "It's not falling for {player} — {d} deaths and counting.": "Lagi nggak jalan buat {player} — {d} kali mati.",

  // ── win probability ────────────────────────────────────────────────
  "The model has {favored} firmly in front — {pct}% to close it out.": "Model naruh {favored} jelas di depan — {pct}% buat nutup.",
  "{favored} in the driver's seat at {pct}% win chance.": "{favored} pegang kendali, {pct}% peluang menang.",
  "The numbers love {favored} here, {pct}% to win it.": "Angkanya condong ke {favored}, {pct}% buat menang.",
  "{favored} heavy favourites now — {pct}% on the model.": "{favored} favorit kuat sekarang — {pct}% di model.",
  "It's {favored}'s to lose, the read sits at {pct}%.": "Tinggal {favored} yang jaga, bacaannya {pct}%.",
  "Momentum swinging toward {to} on the win-probability read.": "Momentum geser ke {to} di bacaan win-probability.",
  "The needle moves for {to} — this is where games turn.": "Jarumnya gerak ke {to} — di sini game biasa berbalik.",
  "{to} tilting the odds their way now.": "{to} mulai narik peluang ke mereka.",
  "Big shift on the model, and it's {to} climbing.": "Pergeseran gede di model, {to} yang naik.",
  "The win probability lurches toward {to}.": "Win probability-nya melonjak ke {to}.",

  // ── hero flavor ────────────────────────────────────────────────────
  "{hero} in the hands of {player} is a real problem right now.": "{hero} di tangan {player} beneran ngeri sekarang.",
  "Watch the {hero} — {player} is finding all the angles.": "Awas {hero}-nya — {player} nemu semua celah.",
  "{player}'s {hero} looking like the pick of the draft.": "{hero}-nya {player} kayak pick terbaik di draft.",
  "{player} has the {hero} humming — a menace in every fight.": "{player} bikin {hero} jalan mulus — ngeri tiap war.",
  "That {hero} pick is paying off for {player}.": "Pick {hero} itu kebayar buat {player}.",
  "{player} making the {hero} look broken right now.": "{player} bikin {hero} keliatan OP banget.",

  // ── general pacing ─────────────────────────────────────────────────
  "Still early doors — both sides settling into the farm.": "Masih early game — dua tim anteng farming.",
  "Opening exchanges, feeling each other out.": "Baru pembukaan, masih saling baca.",
  "Laning phase in full swing, last hits and level leads for now.": "Fase laning rame, rebutan last hit sama unggul level.",
  "Quiet start — everyone's heads down farming.": "Awalan adem — semua fokus farming.",
  "Early game jostling for the jungle and lane priority.": "Early game rebutan jungle sama prioritas lane.",
  "Mid game and the map is opening up — objectives on the horizon.": "Mid game, map mulai kebuka — objektif di depan mata.",
  "Rotations getting sharper as we hit the mid game.": "Rotasi makin rapi pas masuk mid game.",
  "The game's stretching its legs now — expect the fights to start.": "Game mulai panas — siap-siap war pecah.",
  "Cores coming online, and the tempo is picking up.": "Core mulai jadi, tempo naik.",
  "Mid game chess — positioning and vision for the next objective.": "Adu strategi mid game — soal posisi sama vision buat objektif.",
  "Deep into the late game — one fight decides it from here.": "Udah dalem ke late game — satu war nentuin dari sini.",
  "Every pick matters now; there's no respawning your way out of a bad one.": "Tiap pick krusial sekarang; salah dikit nggak ketolong respawn.",
  "The stakes are climbing — full builds and long respawns.": "Taruhannya makin tinggi — build full, respawn lama.",
  "This is the business end; a single mistake could be terminal.": "Ini fase krusial; satu kesalahan bisa fatal.",
  "Late game tension — both sides walking on eggshells around the map.": "Tegang late game — dua tim main hati-hati di map.",
  "We are into the danger zone past 18 minutes — respawns are long and one clean pick ends it.": "Masuk zona bahaya lewat menit 18 — respawn lama, satu pick bersih bisa nutup game.",
  "Every base race and Lord call is match point now — nerves of steel required.": "Tiap base race sama call Lord udah match point — butuh mental baja.",
  "This is where legends are made — a single teamfight from here writes the result.": "Di sinilah legenda lahir — satu war nentuin hasil.",
  "Deep, deep late game — buybacks of momentum only; there's no farming your way back now.": "Late game dalem banget — cuma momentum yang ngomong; nggak bisa farming buat balik.",
  "Sudden-death territory now — one thrown fight and it's over.": "Zona sudden-death — sekali war kebuang, tamat.",
  "Everything on a knife's edge past 18 — the next objective could end it.": "Semua di ujung tanduk lewat menit 18 — objektif berikutnya bisa nutup.",
};

// Win-probability interjection phrasings in Bahasa Indonesia (natural caster).
export const ID_WINPROB = {
  even: [
    "Win probability imbang banget — {teamA} {aPct}%, {teamB} {bPct}%.",
    "Model-nya bingung misahin: {aPct}% / {bPct}%.",
    "Seri di bacaan win-probability, {teamA} {aPct}% lawan {teamB} {bPct}%.",
    "Terlalu tipis buat ditebak — {aPct}% lawan {bPct}% di model.",
    "Nggak ada bedanya: {teamA} {aPct}%, {teamB} {bPct}%.",
  ],
  heavy: [
    "{favored} favorit kuat sekarang — {favPct}% buat menang.",
    "Jarumnya nempel ke {favored} di {favPct}%.",
    "{favored} lagi di atas angin, {favPct}% di model.",
    "Tinggal {favored} yang jaga — {favPct}% di bacaan win-probability.",
    "Model-nya hampir mastiin: {favored} {favPct}%.",
  ],
  lean: [
    "Win probability condong ke {favored} di {favPct}%.",
    "{favored} favorit buat sekarang, {favPct}% buat nutup.",
    "Sedikit unggul buat {favored} — {favPct}% di bacaan.",
    "{favored} maju tipis di model, {favPct}%.",
    "Peluangnya miring ke {favored}, {favPct}% lawan {rest}%.",
  ],
};
